import { Institution } from '@/types/academic-group';

export const MOCK_INSTITUTIONS: Institution[] = [
  {
    id: 'inst-1',
    name: 'Daffodil International University',
    type: 'University',
    district: 'Dhaka',
    city: 'Ashulia',
    website: 'daffodilvarsity.edu.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-2',
    name: 'Bangladesh University of Engineering and Technology (BUET)',
    type: 'University',
    district: 'Dhaka',
    city: 'Palashi',
    website: 'buet.ac.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-3',
    name: 'University of Dhaka (DU)',
    type: 'University',
    district: 'Dhaka',
    city: 'Nilkhet',
    website: 'du.ac.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-4',
    name: 'Dhaka Polytechnic Institute',
    type: 'Polytechnic',
    district: 'Dhaka',
    city: 'Tejgaon',
    website: 'dpi.gov.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-5',
    name: 'Notre Dame College, Dhaka',
    type: 'College',
    district: 'Dhaka',
    city: 'Motijheel',
    website: 'ndc.edu.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-6',
    name: 'BRAC University',
    type: 'University',
    district: 'Dhaka',
    city: 'Merul Badda',
    website: 'bracu.ac.bd',
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'inst-7',
    name: 'Shahjalal University of Science and Technology (SUST)',
    type: 'University',
    district: 'Sylhet',
    city: 'Kumargaon',
    website: 'sust.edu',
    verificationStatus: 'VERIFIED',
  },
];
